### ISSUE TITLE
Error: Unknown arguments configuration,[object Object],[object Object],[object Object],

### ISSUE THREAD

**Issue by allan-bonadio** [sprity/sprity-cli#4]
I'm using the command 

sprity create images spritable/_.png spritable/_.jpg --name gen-sprites --style styles/gen-sprites.css     --prefix spr

This used to work before, but then I upgraded my node version (from 0.10.30 i think) to version 4.  Then when this failed I tried a few more versions; I've tried 4.3.1, 0.10.42 and 0.12.10 .  Still fails.  

The message I get is:

/usr/local/lib/node_modules/lwip/node_modules/decree/dist/cjs/decree.js:80
                    throw Error(errs);
                    ^

Error: Unknown arguments configuration,[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
    at Error (native)
    at /usr/local/lib/node_modules/lwip/node_modules/decree/dist/cjs/decree.js:80:27
    at Object.create (/usr/local/lib/node_modules/lwip/lib/obtain.js:66:33)
    at renderSprite (/usr/local/lib/node_modules/sprity/lib/sprite.js:47:17)
    at createSprite (/usr/local/lib/node_modules/sprity/lib/sprite.js:81:13)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/sprity/lib/sprite.js:124:9)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/usr/local/lib/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/usr/local/lib/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/usr/local/lib/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/usr/local/lib/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/usr/local/lib/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/usr/local/lib/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/usr/local/lib/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/usr/local/lib/node_modules/sprity/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at /usr/local/lib/node_modules/sprity/lib/layout.js:67:16

The number of [Object]s in the message seems related to the number of image files I pass in.  Using macosx 10.9.5

**Comment by ztec** [comment]
probably the same as : https://github.com/sprity/sprity/issues/56

**Comment by renxj** [comment]
![image](https://cloud.githubusercontent.com/assets/19201241/15811937/75806492-2be1-11e6-9811-925ead2dbeff.png)

sprity create "./dist" "src/sprites/*_/_.png"  --background #123456 error

**Comment by frangeris** [comment]
Same issue here :|

``` sh
$ sprity create "./out" "./images/*.png"
/usr/local/lib/node_modules/lwip/node_modules/decree/dist/cjs/decree.js:80
                    throw Error(errs);
                    ^

Error: Unknown arguments configuration,[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
```

**Comment by koh-osug** [comment]
See also https://github.com/sprity/sprity/issues/56 for this.
